name: tts-test

on:
  workflow_dispatch:

jobs:
  run-tts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install TTS
        run: pip install TTS

      - name: Run TTS script
        run: python3 src/test_tts.py
